plugins {
    id 'java'
    id 'io.quarkus'
}

repositories {
    mavenCentral()
    mavenLocal()
    maven {
        url "https://packages.confluent.io/maven"
    }
    maven {
        url "https://repo.akka.io/maven"
    }
}

dependencies {
    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
    implementation(
            'io.quarkus:quarkus-rest',
            'io.quarkus:quarkus-rest-jackson',
            'io.quarkus:quarkus-arc',
            "io.quarkus:quarkus-messaging-kafka",

            // Logger
            "org.jboss.logging:commons-logging-jboss-logging",
            "org.jboss.logmanager:log4j-jboss-logmanager",
            "org.jboss.logmanager:log4j2-jboss-logmanager",
            "org.jboss.slf4j:slf4j-jboss-logmanager",

            // gRPC
            "io.quarkus:quarkus-grpc",
            "io.quarkus:quarkus-rest",
            "io.quarkus:quarkus-arc",

            // Akka
            "com.typesafe.akka:akka-actor-typed_2.13:2.10.9"

    )

    testImplementation(
            'io.quarkus:quarkus-junit5',
            'io.rest-assured:rest-assured'
    )

    compileOnly("org.projectlombok:lombok:1.18.38")
    testCompileOnly("org.projectlombok:lombok:1.18.38")
    testAnnotationProcessor("org.projectlombok:lombok:1.18.38")
    annotationProcessor(
            "org.projectlombok:lombok:1.18.38",
            "org.projectlombok:lombok-mapstruct-binding:0.2.0",
            "org.mapstruct:mapstruct-processor:1.5.5.Final"
    )
}

group 'com.linkinben'
version '1.0.0-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

test {
    systemProperty "java.util.logging.manager", "org.jboss.logmanager.LogManager"
}
compileJava {
    options.encoding = 'UTF-8'
    options.compilerArgs << '-parameters'
}

compileTestJava {
    options.encoding = 'UTF-8'
}