gatling {
    totalAsyncThreads = 64
    minAsyncThreadsPerScenario = 4

    environments {
        local {
            totalTps = 1
            duration = 60
            maxResponseTime = 5000
            timeout = 10
            pollTimeout = 5
            successPercent = 100

            kafka {
                properties {
                    bootstrap.servers = ["localhost:9092"]
                    schema.registry.url = "http://schema-registry:8081"
                    security.protocol = "PLAINTEXT"

                    consumers {
                        default{
                            # Either:
                            # org.apache.kafka.common.serialization.StringSerializer
                            # Or: io.confluent.kafka.serializer.KafkaAvroSerializer
                            key.serializer = "org.apache.kafka.common.serialization.StringSerializer"
                            value.serializer = "org.apache.kafka.common.serialization.StringSerializer"
                            isolationLevel = "read_committed"
                            session.timeout.ms = 10000
                            poll.interval.ms = 100
                        }
                    }

                    producers {
                        default {
                            # Either:
                            # org.apache.kafka.common.serialization.StringSerializer
                            # Or: io.confluent.kafka.serializer.KafkaAvroSerializer
                            key.serializer = "org.apache.kafka.common.serialization.StringSerializer"
                            value.serializer = "org.apache.kafka.common.serialization.StringSerializer"
                        }
                    }
                }

                topic {
                    input = "input-topic.local"
                    output = "output-topic.local"
                }
            }
        }
    }
}