gatling {
    totalAsyncThreads = 10
    minAsyncThreadsPerScenario = 2

    environments {
        local {
            totalTps = 3
            duration = 30
;             maxResponseTime = 10000
;             timeout = 60
;             pollTimeout = 30
;             successPercent = 100

            kafka {
                properties {
                    bootstrap.servers = ["localhost:9092"]
                    schema.registry.url = "http://schema-registry:8081"
                    security.protocol = "PLAINTEXT"
                    poll.interval.ms = 10000

                    consumers {
                        default{
                            # Either:
                            # org.apache.kafka.common.serialization.StringDeserializer
                            # Or: io.confluent.kafka.serializers.KafkaAvroDeserializer
                            group.id = "test"
                            key.serializer = "org.apache.kafka.common.serialization.StringSerializer"
                            value.serializer = "org.apache.kafka.common.serialization.StringSerializer"
                            key.deserializer = "org.apache.kafka.common.serialization.StringDeserializer"
                            value.deserializer = "org.apache.kafka.common.serialization.StringDeserializer"
                            isolationLevel = "read_committed"
                            session.timeout.ms = 10000
                            auto.offset.reset = "latest"
                        }
                    }

                    producers {
                        default {
                            # Either:
                            # org.apache.kafka.common.serialization.StringSerializer
                            # Or: io.confluent.kafka.serializer.KafkaAvroSerializer
                            key.serializer = "org.apache.kafka.common.serialization.StringSerializer"
                            value.serializer = "org.apache.kafka.common.serialization.StringSerializer"
                        }
                    }
                }

                topic {
                    input = "input-topic.local"
                    output = "output-topic.local"
                }
            }
        }
    }
}