gatling {
    charting {
        indicators {
            lowerBound = 400
            higherBound = 800
            percentile1 = 50
            percentile2 = 95
            percentile3 = 99
            percentile4 = 99.95
        }
    }

    http {
        enableGa = false
        warmup = ""
    }
}